ARG GCC_V=14

FROM debian:sid-slim AS llvm_builder

ARG GCC_V
ENV GCC_V=$GCC_V
ENV CCACHE_DIR=/ccache

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  binutils \
  binutils-dev \
  ccache \
  cmake \
  gcc-${GCC_V} \
  gcc-${GCC_V}-plugin-dev \
  g++-${GCC_V} \
  git \
  ninja-build \
  python3

RUN git clone --depth 1 --branch "llvmorg-20.1.1" https://github.com/llvm/llvm-project.git

# Build clang and runtimes
RUN --mount=type=cache,target=/ccache/ \
    cmake -S /llvm-project/llvm \
          -G Ninja \
          -B /llvm-project/build/ \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=gcc-${GCC_V} \
          -DCMAKE_CXX_COMPILER=g++-${GCC_V} \
          -DCMAKE_INSTALL_PREFIX=/llvm_build \
          -DLLVM_BINUTILS_INCDIR=/usr/include \
          -DLLVM_CCACHE_BUILD=ON \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
          -DLLVM_TARGETS_TO_BUILD=Native && \
    ninja -C /llvm-project/build/ "-j$(nproc)" install/strip

# Build a memory sanitizer instrumented libc++
RUN --mount=type=cache,target=/ccache/ \
    cmake -S /llvm-project/runtimes \
          -G Ninja \
          -B /libcxx_msan \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=/llvm_build/bin/clang \
          -DCMAKE_CXX_COMPILER=/llvm_build/bin/clang++ \
          -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
          -DLIBCXX_HARDENING_MODE=debug \
          -DLIBCXX_ABI_DEFINES="_LIBCPP_ABI_BOUNDED_ITERATORS;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_STD_ARRAY;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_STRING;_LIBCPP_ABI_BOUNDED_ITERATORS_IN_VECTOR;_LIBCPP_ABI_BOUNDED_UNIQUE_PTR" \
          -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF \
          -DLLVM_ENABLE_RUNTIMES='libcxx;libcxxabi;libunwind' \
          -DLLVM_TARGETS_TO_BUILD=Native \
          -DLLVM_USE_SANITIZER=MemoryWithOrigins && \
    ninja -C /libcxx_msan "-j$(nproc)"

# We could use the official rust: images here, but they are based on
# earlier versions of Debian, that lead to issues when trying to run
# the sid-built clang from llvm_builder
FROM debian:sid-slim AS rust_builder

COPY --from=llvm_builder /llvm_build* /usr/

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
  curl \
  gcc \
  git \
  libglib2.0-dev \
  make \
  meson \
  ninja-build \
  pkg-config \
  python3-venv

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install rustfilt

#RUN git clone https://github.com/dergoegge/semsan.git
#RUN cd semsan && cargo install --path . --verbose \
#              && cargo install --features qemu_aarch64 --bin semsan-aarch64 --path . \
#              && cargo install --features qemu_arm --bin semsan-arm --path . \
#              && cargo install --features qemu_x86_64 --bin semsan-x86_64 --path . \
#              && cargo install --features qemu_i386 --bin semsan-i386 --path .

WORKDIR /types
COPY ./types/Cargo.toml ./types/Cargo.lock .
RUN mkdir .cargo && cargo vendor > .cargo/config
COPY ./types/src/ src
RUN cargo build --release

WORKDIR /ensemble-fuzz
COPY ./ensemble-fuzz/Cargo.toml ./ensemble-fuzz/Cargo.lock .
RUN mkdir .cargo && cargo vendor > .cargo/config
COPY ./ensemble-fuzz/src/ src
RUN cargo install --path . --verbose

WORKDIR /reproducer
COPY ./reproducer/Cargo.toml ./reproducer/Cargo.lock .
RUN mkdir .cargo && cargo vendor > .cargo/config
COPY ./reproducer/src/ src
RUN cargo install --path . --verbose

WORKDIR /minimizer
COPY ./minimizer/Cargo.toml ./minimizer/Cargo.lock .
RUN mkdir .cargo && cargo vendor > .cargo/config
COPY ./minimizer/src/ src
RUN cargo install --path . --verbose

WORKDIR /builder
COPY ./builder/Cargo.toml ./builder/Cargo.lock .
RUN mkdir .cargo && cargo vendor > .cargo/config
COPY ./builder/src/ src
RUN cargo install --path . --verbose

WORKDIR /fuzzer
COPY ./fuzzer/Cargo.toml ./fuzzer/Cargo.lock .
RUN mkdir .cargo && cargo vendor > .cargo/config
COPY ./fuzzer/src/ src
RUN cargo install --path . --verbose

WORKDIR /coverage-reporter
COPY ./coverage-reporter/Cargo.toml ./coverage-reporter/Cargo.lock .
RUN mkdir .cargo && cargo vendor > .cargo/config
COPY ./coverage-reporter/src/ src
RUN cargo install --path . --verbose

FROM debian:sid-slim

ARG GCC_V
ENV GCC_V=$GCC_V

COPY --from=llvm_builder /llvm_build* /usr/
COPY --from=llvm_builder /libcxx_msan /libcxx_msan
# Be selective, so we don't copy rustc/cargo etc, which may interfere
# with other builds later, i.e rust-lightning
COPY --from=rust_builder /root/.cargo/bin/builder \
                         /root/.cargo/bin/coverage-reporter \
                         /root/.cargo/bin/ensemble-fuzz \
                         /root/.cargo/bin/fuzzer \
                         /root/.cargo/bin/minimizer \
                         /root/.cargo/bin/reproducer \
                         /root/.cargo/bin/semsam* \
                         /usr/local/bin/

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
  autotools-dev \
  automake \
  binutils-dev \
  build-essential \
  ccache \
  cmake \
  curl \
  cpio \
  gcc-${GCC_V}-arm-linux-gnueabihf \
  g++-${GCC_V}-arm-linux-gnueabihf \
  gcc-${GCC_V}-x86-64-linux-gnu \
  g++-${GCC_V}-x86-64-linux-gnu \
  gcc-${GCC_V}-plugin-dev \
  git \
  libtool \
  libunwind-dev \
  libz3-dev \
  linux-perf \
  ninja-build \
  openssh-client \
  pkg-config \
  pax-utils \
  python3 \
  python3-msgpack \
  python3-jinja2 \
  python3-venv \
  rsync

# Build & force mold usage
RUN git clone https://github.com/rui314/mold.git --depth 1 --branch v2.37.1 && \
    cmake -G Ninja -B /mold/build -S mold -DCMAKE_BUILD_TYPE=Release && \
    ninja -C /mold/build/ "-j$(nproc)" install/strip && \
    rm -rf /mold && \
    rm -rf $(which ld) && ln -s $(which mold) /usr/bin/ld

RUN git clone https://github.com/google/honggfuzz.git && \
    make install -C honggfuzz && \
    rm -rf honggfuzz

# Clone AFLplusplus and build
RUN git clone --branch stable https://github.com/AFLplusplus/AFLplusplus && \
    make -C AFLplusplus PERFORMANCE=1 \
                        LLVM_CONFIG=llvm-config \
                        # actually mold
                        AFL_REAL_LD=/usr/bin/ld \
                        -j$(nproc) && \
    make -C AFLplusplus install && \
    rm -rf AFLplusplus

# Install FlameGraph
RUN git clone --depth 1 https://github.com/brendangregg/FlameGraph
ENV FLAMEGRAPH_REPO=/FlameGraph

COPY ./toolchains toolchains

WORKDIR /workdir
RUN mkdir --parents workspace/corpus
RUN mkdir --parents workspace/min_corpus
RUN mkdir --parents workspace/initial_solutions

# Location for the harness binaries
ENV FUZZOR_HARNESSES=/workdir/out

# Some afl++ options
ENV AFL_FUZZER_STATS_UPDATE_INTERVAL=10
ENV AFL_NO_CRASH_README=1
ENV AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
ENV AFL_SKIP_CPUFREQ=1
ENV AFL_HANG_TMOUT=60000

ENV MSAN_LIBCXX_PATH=/libcxx_msan

ENV LLVM_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"
ENV UBSAN_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"
ENV ASAN_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"
ENV MSAN_SYMBOLIZER_PATH="/usr/bin/llvm-symbolizer"

RUN touch ubsan_suppressions
ENV ASAN_OPTIONS="detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:abort_on_error=1:exitcode=75"
ENV UBSAN_OPTIONS="suppressions=/workdir/ubsan_suppressions:print_stacktrace=1:halt_on_error=1:report_error_type=1:exitcode=76"

# Enable env_logger by default with level info
ENV RUST_LOG=trace
