name: Rust

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-crates:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install rust nightly
      run: rustup install nightly && rustup override set nightly

    - name: Build workspace
      run: cargo build --verbose --workspace
    - name: Test workspace
      run: cargo test --verbose --workspace

  validate-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rust nightly
        run: rustup install nightly && rustup override set nightly

      - name: Build validate-configs
        run: |
          cd fuzzor-cmds && cargo build --bin validate-config --release --verbose
          find ../projects/ -type f -name 'config.yaml' -exec target/release/validate-config {} \;


